### ISSUE TITLE
Falha ao baixar a fonte `Inter` do Google fontes

### ISSUE THREAD

**Issue by taffarel55** [OsProgramadores/portalestagio#7]
Log do erro:
```
 ⨯ Failed to download `Inter` from Google Fonts. Using fallback font instead.

Failed to fetch `Inter` from Google Fonts.}
AbortError: The user aborted a request.
    at abort (/home/taffarel55/Repositórios/portalestagio/node_modules/next/dist/compiled/node-fetch/index.js:1:65594)
    at EventTarget.abortAndFinalize (/home/taffarel55/Repositórios/portalestagio/node_modules/next/dist/compiled/node-fetch/index.js:1:65814)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
    at EventTarget.dispatchEvent (node:internal/event_target:757:26)
    at abortSignal (node:internal/abort_controller:374:10)
    at AbortController.abort (node:internal/abort_controller:396:5)
    at Timeout.<anonymous> (/home/taffarel55/Repositórios/portalestagio/node_modules/next/dist/compiled/@next/font/dist/google/fetch-font-file.js:26:55)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  type: 'aborted'
}
AbortError: The user aborted a request.
    at abort (/home/taffarel55/Repositórios/portalestagio/node_modules/next/dist/compiled/node-fetch/index.js:1:65594)
    at EventTarget.abortAndFinalize (/home/taffarel55/Repositórios/portalestagio/node_modules/next/dist/compiled/node-fetch/index.js:1:65814)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
    at EventTarget.dispatchEvent (node:internal/event_target:757:26)
    at abortSignal (node:internal/abort_controller:374:10)
    at AbortController.abort (node:internal/abort_controller:396:5)
    at Timeout.<anonymous> (/home/taffarel55/Repositórios/portalestagio/node_modules/next/dist/compiled/@next/font/dist/google/fetch-font-file.js:26:55)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  type: 'aborted'
}
AbortError: The user aborted a request.
    at abort (/home/taffarel55/Repositórios/portalestagio/node_modules/next/dist/compiled/node-fetch/index.js:1:65594)
    at EventTarget.abortAndFinalize (/home/taffarel55/Repositórios/portalestagio/node_modules/next/dist/compiled/node-fetch/index.js:1:65814)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:822:20)
    at EventTarget.dispatchEvent (node:internal/event_target:757:26)
    at abortSignal (node:internal/abort_controller:374:10)
    at AbortController.abort (node:internal/abort_controller:396:5)
    at Timeout.<anonymous> (/home/taffarel55/Repositórios/portalestagio/node_modules/next/dist/compiled/@next/font/dist/google/fetch-font-file.js:26:55)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  type: 'aborted'
}
```

Node: v21.5.0
Git: 2.43.0

Acredito que isso seja a importação no arquivo `app/ui/fonts.ts`:

```
import { Inter } from 'next/font/google';
```

**Comment by magnussolidus** [comment]
@taffarel55 Por favor, confira se você possui esta fonte em seu sistema. 
O _import_ de fontes costuma ser local, ou seja, do seu equipamento. Se você não tiver a fonte disponível, ele não conseguirá importá-la.

**Comment by taffarel55** [comment]
Ah, tá explicado... Essa fonte seria uma dependência não explícita do nosso projeto, não há isso no README nem está no package.json. Isto parece ferir um dos **Twelve-Factor web**:

Uma aplicação doze-fatores nunca confia na existência implícita de pacotes em todo o sistema.

https://12factor.net/pt_br/dependencies

Pensando nisso eu sugiro a gente remover esta importação para colocar de forma declarativa, o que acha?

**Comment by magnussolidus** [comment]
Discordo que uma fonte seja uma dependência explícita do projeto. Já existe uma [issue para remover código não necessário do app](https://github.com/OsProgramadores/portalestagio/issues/12) e esse tipo de situação pode ser tratada nela.

Creio que este report seja valido, mas não o colocaria como um bug, visto que a execução da aplicação não é impedida pela ausência da fonte citada.

Outra coisa importante: você não simplesmente atribui a issue a si antes de ter um retorno sobre. Você abriu a issue e já a atribuiu a ti, sem nenhum parecer de ninguém. Isso não é recomendado.

**Comment by mpinheir** [comment]
@taffarel55 o que você rodou para aparecer este erro?
Aqui não está dando erro não.

Outra coisa, recomendo usar a mais recente LTS version do NodeJS. A atual é a v20.11.1
Me parece que estás usando uma mais recente e não LTS.

**Comment by magnussolidus** [comment]
@taffarel55 Pode conferir se o comportamento se repete para você usando a versão LTS mencionada acima? 

Entendo que você desatribuiu a issue por conta do meu comentário anterior, mas como você já está atuando nela, agora vai ficar contigo, ok? :)

**Comment by taffarel55** [comment]
@mpinheir, executei o `npm run dev` após ter instalado as dependências com o `npm install`. Irei usar o nvm e mudar para a última LTS.

@magnussolidus Vou verificar com a versão LTS. Eu me atribui à tarefa pra ser proativo mesmo e não apenas reportar algo e não se propor para resolver :smiley:

**Comment by magnussolidus** [comment]
@taffarel55 alguma novidade?

**Comment by magnussolidus** [comment]
Status no Project movido para OnHold até recebermos uma nova atualização.

**Comment by magnussolidus** [comment]
Issue fechada, marcada como nada a ser feito.
Motivo: falta de atualizações sobre o bug.
